### ISSUE TITLE
Sometimes when creating a new AWS EC2 Windows Server receiving ERROR: Batch render command returned 401

### ISSUE THREAD

**Issue by rcsavage** [chef/knife-ec2#329] opened 2015-07-09 19:40 UTC
Sometimes when I provision a new server with knife ec2, I get the error messages below.  It's not always the case, but randomly.   Basically the provisioning works up to a point prior to the chef client install and errors with "ERROR: Batch render command returned 401".  I have not been able to determine a pattern or reason why this is occurring.  I suspect it's something to do with AWS, but I am not sure.  If I rerun the same step, it usually works.  It's like an access or race condition type of thing.

provision_mstr_iserver 
Instance ID: i-2f08add1
Flavor: m3.large
Image: ami-5b9e6b30
Region: us-east-1
Availability Zone: us-east-1a
Security Group Ids: sg-c29c78a5
IAM Profile: mstr-iserver
Tags: Name: rsavage-iserver
SSH Key: rory_savage

Waiting for EC2 to create the instance...........................
Public DNS Name: ec2-52-2-81-202.compute-1.amazonaws.com
Public IP Address: 52.2.81.202
Private DNS Name: ip-172-31-11-9.ec2.internal
Private IP Address: 172.31.11.9

Waiting for winrm access to become available.done

Waiting for Windows Admin password to be available
Waiting for remote response before bootstrap.......ec2-52-2-81-202.compute-1.amazonaws.com . 
ec2-52-2-81-202.compute-1.amazonaws.com Response received.
Remote node responded after 0.5 minutes.
Bootstrapping Chef on ec2-52-2-81-202.compute-1.amazonaws.com
ec2-52-2-81-202.compute-1.amazonaws.com "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-13607-1436470297.bat" chunk 1" 
ec2-52-2-81-202.compute-1.amazonaws.com "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-13607-1436470297.bat" chunk 2" 
ec2-52-2-81-202.compute-1.amazonaws.com "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-13607-1436470297.bat" chunk 3" 
ec2-52-2-81-202.compute-1.amazonaws.com "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-13607-1436470297.bat" chunk 4" 
ec2-52-2-81-202.compute-1.amazonaws.com "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-13607-1436470297.bat" chunk 5" 
ec2-52-2-81-202.compute-1.amazonaws.com "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-13607-1436470297.bat" chunk 6" 
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Batch render command returned 401
ERROR: Bootstrap command returned 401

Instance ID: i-2f08add1
Flavor: m3.large
Image: ami-5b9e6b30
Region: us-east-1
Availability Zone: us-east-1a
Security Groups: default
Security Group Ids: sg-c29c78a5
IAM Profile: mstr-iserver
Tags: Name: rsavage-iserver
SSH Key: rory_savage
Root Device Type: ebs
Root Volume ID: vol-659c4f9e
Root Device Name: /dev/sda1
Root Device Delete on Terminate: true

**Comment by dheerajd-msys** [comment] 2016-12-05 12:02
@rcsavage Since this is an intermittent error, I couldn't reproduce the error. However after investigation I found similar knife-windows issue  https://github.com/chef/knife-windows/issues/143. This is kind of **WinRM::WinRMHTTPTransportError** and also it seems from your command output that server gets created and bootstrapped successfully. Are you running your command with HTTP_PROXY environment variable set. If so please clear and check again. 
If it's possible, can you please send the command parameters that you used and use case?

**Comment by dheerajd-msys** [comment] 2016-12-09 13:43
Closing this issue for now, hope above comments help you. Please feel free to re-open if error is still there.

**Closed by dheerajd-msys** 2016-12-09 13:43 UTC
